# BC5 - Demand Forecast

In [1]:
import pandas as pd

#  1- Load the dataset

Because of the size and the weight of the dataset we had to load  the dataset in chunks of 10M Rows
After the creation of each chunk we upload each chunk to a different csv fille to be easier to read the filles in the future

In [9]:
batch_no = 1
for chunk in pd.read_csv('data.csv', chunksize=10000000):
    chunk.to_csv('chunkfile' + str(batch_no) + '.csv', index=False)
    batch_no +=1

To understand what could be donne with the dataset we load him with only 5 rows

In [3]:
pd.read_csv(r'C:\Users\classroom\Documents\b5data\data.csv', nrows=100)

,ProductFamily_ID,ProductCategory_ID,ProductBrand_ID,ProductName_ID,ProductPackSKU_ID,Point-of-Sale_ID,Date,Measures,Value
0,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-03-04,Sell-out units,2
1,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-03-04,Sell-out values,1540
2,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-05-02,Sell-out units,4
3,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-05-02,Sell-out values,3080
4,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-24,Sell-out units,2
5,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-24,Sell-out values,1540
6,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-13,Sell-out units,2
7,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-14,Sell-out units,2
8,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-15,Sell-out units,2
9,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-13,Sell-out values,1620
10,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-14,Sell-out values,1620
11,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-15,Sell-out values,1620
12,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-03-29,Sell-out units,2
13,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-03-29,Sell-out values,1540
14,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-19,Sell-out units,2
15,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-24,Sell-out units,2
16,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-26,Sell-out units,2
17,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-19,Sell-out values,1620
18,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-24,Sell-out values,1620
19,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2017-10-26,Sell-out values,1620
20,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-17,Sell-out units,2
21,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-22,Sell-out units,2
22,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-28,Sell-out units,2
23,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-17,Sell-out values,1540
24,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-22,Sell-out values,1540
25,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-06-28,Sell-out values,1540
26,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-07,Sell-out units,2
27,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-13,Sell-out units,2
28,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-07,Sell-out values,1540
29,Family_16,Category_11,ProductBrand_306,ProductName_649,ProductSKU_1970,POS_1,2016-10-13,Sell-out values,1540
...,...,...,...,...,...,...,...,...,...
70,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-12-14,Sell-out units,3
71,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-12-14,Sell-out values,2673
72,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-10-16,Sell-out units,2
73,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-10-30,Sell-out units,2
74,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-10-16,Sell-out values,1782
75,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-10-30,Sell-out values,1782
76,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-02,Sell-out units,4
77,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-04,Sell-out units,2
78,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-13,Sell-out units,2
79,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-02,Sell-out values,3564
80,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-04,Sell-out values,1782
81,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-05-13,Sell-out values,1782
82,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-02-01,Sell-out units,2
83,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-02-02,Sell-out units,2
84,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-02-01,Sell-out values,1782
85,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2016-02-02,Sell-out values,1782
86,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-02-18,Sell-out units,2
87,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-02-18,Sell-out values,1782
88,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-06-29,Sell-out units,2
89,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-06-29,Sell-out values,1782
90,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-09-18,Sell-out units,3
91,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-09-18,Sell-out values,2673
92,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-12-17,Sell-out units,3
93,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2018-12-17,Sell-out values,2673
94,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-09-13,Sell-out units,2
95,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2019-09-13,Sell-out values,1782
96,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2017-10-10,Sell-out units,2
97,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2017-10-10,Sell-out values,1782
98,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2017-07-06,Sell-out units,2
99,Family_6,Category_178,ProductBrand_744,ProductName_1422,ProductSKU_4424,POS_1,2017-07-12,Sell-out units,2

In the previows table it's visible that 7/9 columns have information that will not be needed to the analisies and that make the dataset heavy.
So we created a function that will clean those columms and make the dataset much lighter.
To avoid memory problems we will run this cleaning function in the chunks and not in the all datset together.

In [7]:
def pre_process(ds):
    ds['ProductFamily_ID'] = ds['ProductFamily_ID'].str.split('_').str[1]
    ds['ProductCategory_ID'] = ds['ProductCategory_ID'].str.split('_').str[1]
    ds['ProductBrand_ID'] = ds['ProductBrand_ID'].str.split('_').str[1]
    ds['ProductName_ID'] = ds['ProductName_ID'].str.split('_').str[1]
    ds['ProductPackSKU_ID'] = ds['ProductPackSKU_ID'].str.split('_').str[1]
    ds['Point-of-Sale_ID'] = ds['Point-of-Sale_ID'].str.split('_').str[1]
    ds['Measures'] = ds['Measures'].str.split(' ').str[1]
    ds['Date'] = pd.to_datetime(ds['Date'])
    dS = ds.sort_values(by='Date')

In [8]:
for no in range(1,20):
    df = pd.read_csv('chunkfile' + str(no) + '.csv')
    pre_process(df)
    df.to_csv('chunk_after_preproc' + str(no) + '.csv', index=False)

Merge all the the chunk csv that are already clean and lighter in only one csv fille

In [ ]:
#correr mais tarde para testar
a1 = pd.read_csv('chunk_after_preproc1.csv')

for no in range(2,20):
    a1 = a1.append(pd.read_csv('chunk_after_preproc' + str(no) + '.csv'))
  

a1

MemoryError:

In [ ]:
a1.to_csv('merge1', index=False)